### PR TITLE
fix: reject txs from the mempool that have a PFB but not a blob

### LINKED ISSUE #1165: Reject PFB transactions from the mempool without blobs attached
We don't actually test for or enforce that a PFB transaction must have a blob attached when being submitted to the mempool. This will result in a block producer including a PFB without a blob!

related to #1164

### PR DESCRIPTION
**Pull request by evan-forbes**
## Overview

fixes two bugs, one where we were creating PFD transactions without actually wrapping them with a blob :face_with_spiral_eyes:, and then another bug where we should have been checking for that during checkTx. 

closes #1165 
blocking, and related to #1168 

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

### CODE REVIEW

File: app/test/block_size_test.go [hunk 1]
```diff
@@ -247,6 +249,28 @@ func (s *IntegrationTestSuite) TestSubmitWirePayForBlob() {
 	}
 }
 
+func (s *IntegrationTestSuite) TestUnmalleatedPFBRejection() {
```
Comment (evan-forbes) [inline app/test/block_size_test.go:252]: will change name in a second

**Review by evan-forbes — COMMENTED** [review]
we should probably turn this entire thing into an antehandler #1166

File: x/blob/client/cli/wirepayfordata.go [hunk 2]
```diff
@@ -54,11 +58,89 @@ func CmdWirePayForBlob() *cobra.Command {
...
 	return cmd
 }
+
+// writeTx attempts to generate and sign a transaction using the normal
+// cosmos-sdk cli argument parsing code with the given set of messages. It will also simulate gas
+// requirements if necessary. It will return an error upon failure.
+//
+// NOTE: Copy paste forked from the cosmos-sdk so that we can wrap the PFB with
+// a blob while still using all of the normal cli parsing code
+func writeTx(clientCtx client.Context, txf sdktx.Factory, msgs ...sdk.Msg) ([]byte, error) {
```
Comment (evan-forbes) [inline x/blob/client/cli/wirepayfordata.go:92]: had to copy and paste this from the cosmos-sdk so that we can wrap the tx with a blob before broadcasting it.

File: x/blob/client/testutil/integration_test.go [hunk 3]
```diff
@@ -123,12 +124,9 @@ func (s *IntegrationTestSuite) TestSubmitWirePayForBlob() {
...
 
 			// attempt to query for the malleated transaction using the original tx's hash
-			qTxCmd := authcmd.QueryTxCmd()
-			out, err = clitestutil.ExecTestCLICmd(clientCtx, qTxCmd, []string{txResp.TxHash, "--output=json"})
+			res, err := testfactory.QueryWithoutProof(clientCtx, txResp.TxHash)
 			require.NoError(err)
-
-			var result sdk.TxResponse
-			s.Require().NoError(val.ClientCtx.Codec.UnmarshalJSON(out.Bytes(), &result))
+			require.Equal(abci.CodeTypeOK, res.TxResult.Code)
```
Comment (evan-forbes) [inline x/blob/client/testutil/integration_test.go:129]: we have to use the normal query mechanism, and not the this one because the cosmos-sdk mocks the inputs and outputs, which doesn't know how to decode a blob transaction.

File: x/blob/types/errors.go [hunk 4]
```diff
@@ -27,4 +27,5 @@ var (
 	ErrNamespaceMismatch              = sdkerrors.Register(ModuleName, 11127, "namespace of blob and its respective MsgPayForBlob differ")
 	ErrProtoParsing                   = sdkerrors.Register(ModuleName, 11128, "failure to parse a transaction from its protobuf representation")
 	ErrMultipleMsgsInBlobTx           = sdkerrors.Register(ModuleName, 11129, "not yet supported: multiple sdk.Msgs found in BlobTx")
+	ErrBloblessPFB                    = sdkerrors.Register(ModuleName, 11130, "MsgPayForBlob transactions must be paird with a blob")
```
Comment (cmwaters) [inline x/blob/types/errors.go:30]:
```suggestion
	ErrBloblessPFB                    = sdkerrors.Register(ModuleName, 11130, "MsgPayForBlob transactions must be paired with a blob")
```

**Review by cmwaters — APPROVED** [review]
Good catch!

**Review by rahulghangas — COMMENTED** [review]
Fist pass looks good. Small nit. Will do a second pass before approving

File: app/check_tx.go [hunk 5]
```diff
@@ -4,6 +4,7 @@ import (
 	"fmt"
 
 	"github.com/celestiaorg/celestia-app/x/blob/types"
+	blobtypes "github.com/celestiaorg/celestia-app/x/blob/types"
```
Comment (rootulp) [inline app/check_tx.go:7]: [nit] we can remove the duplicate import statement if we always use the import alias in this file

```suggestion
	blobtypes "github.com/celestiaorg/celestia-app/x/blob/types"
```

File: x/blob/types/errors.go (hunk 4 above)
Comment (rootulp) [reply x/blob/types/errors.go:30]: [optional] alternative error message

```suggestion
	ErrBloblessPFB                    = sdkerrors.Register(ModuleName, 11130, "transaction that contains a MsgPayForBlob must also contain a blob")
```

**Review by rootulp — DISMISSED** [review]

**Review by rahulghangas — APPROVED** [review]

File: app/test/block_size_test.go [hunk 6]
```diff
@@ -247,6 +250,28 @@ func (s *IntegrationTestSuite) TestSubmitWirePayForBlob() {
...
+		false,
+		s.cfg.ChainID,
+		s.accounts[:1],
+	)
+
+	btx, isBlob := coretypes.UnmarshalBlobTx(blobTx[0])
+	require.True(t, isBlob)
+
+	res, err := val.ClientCtx.BroadcastTxSync(btx.Tx)
+	require.NoError(t, err)
```
[the remark this answers is not in the document]
Comment (evan-forbes) [reply app/test/block_size_test.go:271]: yeah, good point, we should definitely be more consistent. I have been moving towards just using t, mainly because its less of a change between test suite tests and normal tests. also its one less thing we have to declare each test.

File: app/check_tx.go (hunk 5 above)
Comment (evan-forbes) [reply app/check_tx.go:7]: damn I though the linter would pick up on this!

Comment (evan-forbes) [reply app/check_tx.go]: damn, we were doing this in a few places 1895fa48486c54a38acc50ada27c336e5f2c215b

Comment (evan-forbes) [reply app/check_tx.go]: good catch!

**Review by rahulghangas — APPROVED** [review]
