### PR TITLE
fix: e2e tests

### LINKED ISSUE #3453: e2e tests are currently not working
## Context

```
--> Running end to end tests
go run ./test/e2e 
test-e2e2024/0[5](https://github.com/celestiaorg/celestia-app/actions/runs/8997023702/job/24714448567#step:5:6)/08 06:01:04 No particular test specified. Running all tests.
test-e2e2024/05/08 0[6](https://github.com/celestiaorg/celestia-app/actions/runs/8997023702/job/24714448567#step:5:7):01:04 go run ./test/e2e <test_name> to run a specific test
test-e2e2024/05/08 06:01:04 Valid tests are: MinorVersionCompatibility, MajorUpgradeToV2, E2ESimple

test-e2e2024/05/0[8](https://github.com/celestiaorg/celestia-app/actions/runs/8997023702/job/24714448567#step:5:9) 06:01:04 === RUN MinorVersionCompatibility
test-e2e2024/05/08 06:01:04 no versions to test
exit status 1
make: *** [Makefile:140: test-e2e] Error 1
```

https://github.com/celestiaorg/celestia-app/actions/runs/8997023702/job/24714448567

```
test-e2e2024/05/15 16:35:44 Starting testnet
2024/05/15 16:37:50 Failed to start testnet: node val0 failed to start: forwarding port 26657: error forwarding port after 5 retries: timed out waiting for port forwarding to be ready
exit status 1
```
https://github.com/celestiaorg/celestia-app/actions/runs/9099118540/job/25011842760?pr=3487

```
2024/05/17 10:38:49 Failed to start testnet: node val0 failed to start: error waiting for instance 'val0-ee2a49ab' to be running: timeout while waiting for instance 'val0-ee2a49ab' to be running
exit status 1
```

https://github.com/celestiaorg/celestia-app/actions/runs/9126237806/job/25095937942?pr=3487

## Problem

e2e tests are failing locally and also in the nightly workflow. 

## Proposal

Fix it so it passes

[Optional follow-up] Instead of running it nightly, run it on every PR and make it an optional check. Currently, no one notices when the nightly fails because we have no hooks set up to alert us of failures.

### PR DESCRIPTION
**Pull request by ninabarbakadze**
## Overview

Fixes #3453 

I encountered a lot of flakiness while running knuu tests in ci(view logs in issue description) to resolve them i added a few workarounds with @smuu which broke other things in our existing suite. those changes are now reverted since the tests started passing on main again after scaling some of the clusters that were stuck. DevOps is working on addressing flakiness on knuu.

E2E tests are green: https://github.com/celestiaorg/celestia-app/actions/runs/9179315870/job/25241185362?pr=3487

My changes:
-  Fix git tag fetching issue
-  Extract e2e tests into its own yaml file
-  Separate MinorVersionCompatibility and MajorupgradeToV2

### CODE REVIEW

File: test/e2e/testnet/node.go [hunk 1]
```diff
@@ -199,11 +199,15 @@ func (n *Node) Init(genesis *types.GenesisDoc, peers []string, configOptions ...
...
+	if err := n.Instance.Commit(); err != nil {
+		return fmt.Errorf("committing instance: %w", err)
+	}
+
 	if err := n.Instance.AddFolder(nodeDir, remoteRootDir, "10001:10001"); err != nil {
 		return fmt.Errorf("copying over node %s directory: %w", n.Name, err)
 	}
 
-	return n.Instance.Commit()
+	return nil
```
Comment (staheri14) [inline test/e2e/testnet/node.go:210]: Swapping the order of these two function calls makes the tests fail, in specific, I ran `E2ESimple`.  Below is the log of the first validator which constantly fails to start:
```
2024-05-21 15:01:07.141 | cp: can't stat '/home/celestia/.celestia-app/*': No such file or directory |  
-- | -- | --
  |   | 2024-05-21 15:00:13.162 | cp: can't stat '/home/celestia/.celestia-app/*': No such file or directory |  
  |   | 2024-05-21 14:59:44.139 | cp: can't stat '/home/celestia/.celestia-app/*': No such file or directory |  
  |   | 2024-05-21 14:59:30.184 | cp: can't stat '/home/celestia/.celestia-app/*': No such file or directory
```

**Review by staheri14 — CHANGES_REQUESTED** [review]

File: test/e2e/main.go [hunk 2]
```diff
@@ -40,7 +40,7 @@ func main() {
 
 	if !specificTestFound {
 		logger.Println("No particular test specified. Running all tests.")
-		logger.Println("go run ./test/e2e <test_name> to run a specific test")
+		logger.Println("make test <test_name> to run a specific test")
```
[the remark this answers is not in the document]
Comment (ninabarbakadze) [reply test/e2e/main.go:43]: it's supposed to be make test-e2e. i'm changing it now.

File: test/e2e/testnet/node.go (hunk 1 above)
Comment (ninabarbakadze) [reply test/e2e/testnet/node.go:210]: interesting, it was still passing for me and also in CI. but apparently this performance improvement is only available in version 13.3

File: .github/workflows/e2e-tests.yml [hunk 3]
```diff
@@ -0,0 +1,27 @@
+name: test-e2e
```
Comment (rootulp) [inline .github/workflows/e2e-tests.yml:1]: [optional] can the file name please match the workflow name so it's easy to jump from one to the other? 

Concretely the file name should be test-e2e.yml if that's the name used here.

File: test/e2e/major_upgrade_v2.go [hunk 4]
```diff
@@ -0,0 +1,142 @@
...
+	"github.com/celestiaorg/celestia-app/v2/app/encoding"
+	v1 "github.com/celestiaorg/celestia-app/v2/pkg/appconsts/v1"
+	v2 "github.com/celestiaorg/celestia-app/v2/pkg/appconsts/v2"
+	"github.com/celestiaorg/celestia-app/v2/test/e2e/testnet"
+	"github.com/celestiaorg/celestia-app/v2/test/txsim"
+	"github.com/celestiaorg/knuu/pkg/knuu"
+	"github.com/tendermint/tendermint/rpc/client/http"
+)
+
+func MajorUpgradeToV2(logger *log.Logger) error {
```
Comment (rootulp) [inline test/e2e/major_upgrade_v2.go:21]: thanks for splitting this out to a separate file

File: test/e2e/major_upgrade_v2.go [hunk 5]
```diff
@@ -0,0 +1,142 @@
...
+
+	logger.Println("Creating genesis nodes")
+	for i := 0; i < numNodes; i++ {
+		err := testNet.CreateGenesisNode(latestVersion, 10000000, upgradeHeight, testnet.DefaultResources)
+		testnet.NoError("failed to create genesis node", err)
+	}
+
+	kr, err := testNet.CreateAccount("alice", 1e12, "")
+	testnet.NoError("failed to create account", err)
+	// start the testnet
```
Comment (rootulp) [inline test/e2e/major_upgrade_v2.go:54]: comment is redundant considering there is a log a few lines down that actually says "Starting testnet"

```suggestion
```

File: test/e2e/major_upgrade_v2.go [hunk 6]
```diff
@@ -0,0 +1,142 @@
...
+	errCh := make(chan error)
+	encCfg := encoding.MakeConfig(app.ModuleEncodingRegisters...)
+	opts := txsim.DefaultOptions().WithSeed(seed).SuppressLogs()
+	sequences := txsim.NewBlobSequence(txsim.NewRange(200, 4000), txsim.NewRange(1, 3)).Clone(5)
+	sequences = append(sequences, txsim.NewSendSequence(4, 1000, 100).Clone(5)...)
+	go func() {
+		errCh <- txsim.Run(ctx, testNet.GRPCEndpoints()[0], kr, encCfg, opts, sequences...)
+	}()
+
+	// assert that the network is initially running on v1
```
Comment (rootulp) [inline test/e2e/major_upgrade_v2.go:70]: this comment seems placed incorrectly because the contents of the for loop below actually assert that the network is on v1 for certain headers and v2 for other headers. Proposal to get rid of the comment entirely

```suggestion
```

File: test/e2e/major_upgrade_v2.go [hunk 7]
```diff
@@ -0,0 +1,142 @@
...
+		testnet.NoError("failed to get header", err)
+		logger.Println("Node", i, "is running on version", resp.Header.Version.App)
+		if resp.Header.Version.App != v1.Version {
+			return fmt.Errorf("version mismatch before upgrade: expected %d, got %d", v1.Version, resp.Header.Version.App)
+		}
+
+		resp, err = client.Header(ctx, &upgradeHeight)
+		testnet.NoError("failed to get header", err)
+		if resp.Header.Version.App != v2.Version {
+			return fmt.Errorf("version mismatch before upgrade: expected %d, got %d", v2.Version, resp.Header.Version.App)
```
Comment (rootulp) [inline test/e2e/major_upgrade_v2.go:88]: I think this error message is wrong

```suggestion
			return fmt.Errorf("version mismatch after upgrade: expected %d, got %d", v2.Version, resp.Header.Version.App)
```

**Review by rootulp — COMMENTED** [review]
[question] out of curiosity how was the git tag issue fixed?

File: .github/workflows/e2e-tests.yml [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+      KNUU_KUBECONFIG_FILE:
+        required: true
+
+jobs:
+  test-e2e:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
```
Comment (ninabarbakadze) [inline .github/workflows/e2e-tests.yml:15]: I fixed the tags issue by adding `fetch-depth: 0` @rootulp

Comment (rootulp) [reply .github/workflows/e2e-tests.yml:15]: thanks! Looks like that will fetch all tags so SGTM

File: .github/workflows/e2e-tests.yml (hunk 3 above)
Comment (ninabarbakadze) [reply .github/workflows/e2e-tests.yml]: done

**Review by rootulp — APPROVED** [review]
👍

File: test/e2e/main.go [hunk 9]
```diff
@@ -40,7 +40,7 @@ func main() {
 
 	if !specificTestFound {
 		logger.Println("No particular test specified. Running all tests.")
-		logger.Println("go run ./test/e2e <test_name> to run a specific test")
+		logger.Println("make test-e2e <test_name> to run a specific test")
 		logger.Printf("Valid tests are: %s\n\n", getTestNames(tests))
```
Comment (cmwaters) [inline test/e2e/main.go:44]: nit: Does this need to be printed? Doesn't each test usually print their names upon start?

**Review by cmwaters — APPROVED** [review]

**Review by evan-forbes — APPROVED** [review]

File: test/e2e/major_upgrade_v2.go [hunk 10]
```diff
@@ -0,0 +1,140 @@
...
+	testnet.NoError("failed to add image", preloader.AddImage(testnet.DockerImageName(latestVersion)))
+
+	logger.Println("Creating genesis nodes")
+	for i := 0; i < numNodes; i++ {
+		err := testNet.CreateGenesisNode(latestVersion, 10000000, upgradeHeight, testnet.DefaultResources)
+		testnet.NoError("failed to create genesis node", err)
+	}
+
+	kr, err := testNet.CreateAccount("alice", 1e12, "")
+	testnet.NoError("failed to create account", err)
```
Comment (evan-forbes) [inline test/e2e/major_upgrade_v2.go:53]: nit for future:

if we move files, ideally (I haven't always done this!) we only move them and not change anything to reduce the effort to see what actually changed. in this case it looked like it was just some comments

Comment (ninabarbakadze) [reply test/e2e/major_upgrade_v2.go:53]: yeah I tend to agree but since it was only minor changes I applied suggestions

**Review by staheri14 — APPROVED** [review]
