### PR TITLE
fix: tokenfilter test

### LINKED ISSUE #3238: Fix tokenfilter tests
### Summary

Right now our token filter tests have been commented out:

https://github.com/celestiaorg/celestia-app/blob/897b448cb8d2b655743bf1e786f6823775468964/test/tokenfilter/tokenfilter_test.go#L135-L141

The reason being that the app version isn't passed in the header (so the tests simply panic).

We should fix this and re-enable the tests. Currently they rely on the `testing` package provided by the ibc-go repo. It's possible to suggest the fix there. The problem is that we would want the changes backported to the v6.x branch which is no longer supported (only v7 and v8 are supported). I would prefer not to have to fork another repo so the options would be to:

1. Rewrite the tests using `interchaintest` (the docker image based one that strangelove maintain)
2. Upgrade to v8 in v2 and submit the patch that supports different app versions

### PR DESCRIPTION
**Pull request by ninabarbakadze**
## Overview

Fixes #3238

### CODE REVIEW

File: test/tokenfilter/setup.go [hunk 1]
```diff
@@ -10,6 +10,8 @@ import (
 	"github.com/celestiaorg/celestia-app/v2/app/encoding"
 	"github.com/celestiaorg/celestia-app/v2/pkg/appconsts"
 	"github.com/celestiaorg/celestia-app/v2/test/util/testnode"
+
```
Comment (rootulp) [inline test/tokenfilter/setup.go:13]: I think this newline is unintentional

```suggestion
```

File: test/tokenfilter/tokenfilter_test.go [hunk 2]
```diff
@@ -136,6 +136,5 @@ func TestTokenFilterTestSuite(t *testing.T) {
 	// FIXME: this is because the ibctesting framework we use
 	// doesn't set the version in the header which we require
 	// to know which state machine to execute against
```
Comment (rootulp) [inline test/tokenfilter/tokenfilter_test.go:138]: [blocking] this comment appears no longer relevant

**Review by rootulp — APPROVED** [review]
Thanks!

**Review by evan-forbes — APPROVED** [review]
