### PR TITLE
fix(test/util): legacy genesis should use `app_version`

### LINKED ISSUE #4814: test-e2e times out
## Context

Last commit on main

https://github.com/celestiaorg/celestia-app/actions/runs/15008167375/job/42171702365

## Problem

test-e2e times out after running for 6 hours

### PR DESCRIPTION
**Pull request by chatton**
## Overview

The genesis file needs to be populated with the correct values expected by v3, we can't use the type directly as it has been modified so we need to update the bz directly.

closes #4814

### CODE REVIEW

**Comment by evan-forbes** [comment]
did we want to merge this or is this added elsewhere?

**Comment by chatton** [comment]
Ah yeah sorry forgot about this one 😅 , I think this logic is still correct but it's not being hit anywhere 'cause it was only in the v4 upgrade tests. I think we can still merge it since we'll want to have those upgrade tests anyway and this will make it a bit more obvious what the v3 genesis should look like.

File: test/util/genesis/legacy_genesis.go [hunk 1]
```diff
@@ -78,6 +79,18 @@ func DocumentLegacyBytes(
...
+	bz, err = maps.SetField(bz, "consensus_params.version.app_version", strconv.Itoa(int(cp.Version.App)))
+	if err != nil {
+		return nil, fmt.Errorf("adding app_version field: %w", err)
+	}
+
+	// remove the version from the new location.
+	bz, err = maps.RemoveField(bz, "consensus_params.version.app")
+	if err != nil {
+		return nil, fmt.Errorf("removing version.app field: %w", err)
+	}
```
Comment (rootulp) [inline test/util/genesis/legacy_genesis.go:92]: Thanks. 

[no change needed] It was a huge pain that Cosmos SDK v0.50.x broke the format of the genesis file. This has come up a few times. Most recently still in:
- https://github.com/celestiaorg/celestia-app/issues/4780
- https://github.com/celestiaorg/celestia-app/pull/5010

**Review by rootulp — APPROVED** [review]
LGTM if CI passes. Out of curiosity, which tests were failing prior to this PR?

**Comment by chatton** [comment]
> LGTM if CI passes. Out of curiosity, which tests were failing prior to this PR?
> 
> Update: looks like `test-e2e` but I think they've been replaced by test-docker-e2e and the upgrade tests aren't running in CI. 

currently no tests are actually using this since the knuu ones are removed, the main reason to merge this is to highlight the expected state of the genesis file for future upgrade tests using tastora.

File: test/util/genesis/legacy_genesis.go [hunk 2]
```diff
@@ -78,6 +79,18 @@ func DocumentLegacyBytes(
...
 	}
 
+	// the version field used to be at this consensus_params.version.app_version
+	bz, err = maps.SetField(bz, "consensus_params.version.app_version", strconv.Itoa(int(cp.Version.App)))
+	if err != nil {
+		return nil, fmt.Errorf("adding app_version field: %w", err)
+	}
+
+	// remove the version from the new location.
+	bz, err = maps.RemoveField(bz, "consensus_params.version.app")
```
Comment (rach-id) [inline test/util/genesis/legacy_genesis.go:89]: to confirm my understanding, the `app_version` field was renamed to `app` and since this test might start using a v3 app version, we need to use the old name, right?

if so, shouldn't we keep both in case the test was started using v4 app?

Comment (rootulp) [reply test/util/genesis/legacy_genesis.go:89]: If the test was started using a v4 app then the multiplexer should be able to read genesis files that use the old format.

Comment (chatton) [reply test/util/genesis/legacy_genesis.go:89]: this code path is just for a v3 genesis, there is a separate codepath for v4, the legacy_genesis.go file was just added to handle older versions.
