### PR TITLE
test: pfm integration

### LINKED ISSUE #3651: Integration test PFM
## Context

We added PFM to v2 but we don't have a test to prevent regressions.

## Problem

Nina tried adding a PFM end-to-end test with interchaintest but that was flaky. See https://github.com/celestiaorg/celestia-app/issues/3241

## Proposal

Write a unit test for PFM behavior. Optionally use ibc-go. Note: this doesn't strictly block v2 release but it is a nice to have.

### PR DESCRIPTION
**Pull request by ninabarbakadze**
## Overview

Fixes #3651

### CODE REVIEW

**Review by cmwaters — APPROVED** [review]
🎉 great job!

File: test/pfm/pfm_test.go [hunk 1]
```diff
@@ -0,0 +1,237 @@
...
+	Receiver       string        `json:"receiver"`
+	Port           string        `json:"port"`
+	Channel        string        `json:"channel"`
+	Timeout        time.Duration `json:"timeout"`
+	Retries        *uint8        `json:"retries,omitempty"`
+	Next           *string       `json:"next,omitempty"`
+	RefundSequence *uint64       `json:"refund_sequence,omitempty"`
+}
+
+func SetupTest(t *testing.T) (*ibctesting.Coordinator, *ibctesting.TestChain,
```
Comment (rootulp) [inline test/pfm/pfm_test.go:35]: [question] given this is a setup function, I think it can be private.

File: test/pfm/pfm_test.go [hunk 2]
```diff
@@ -0,0 +1,237 @@
...
+	celestiaChain := utils.NewTestChain(t, coordinator, ibctesting.GetChainID(1))
+	chainA := NewTestChain(t, coordinator, ibctesting.GetChainID(2))
+	chainB := NewTestChain(t, coordinator, ibctesting.GetChainID(3))
+	coordinator.Chains[ibctesting.GetChainID(1)] = celestiaChain
+	coordinator.Chains[ibctesting.GetChainID(2)] = chainA
+	coordinator.Chains[ibctesting.GetChainID(3)] = chainB
+	return coordinator, chainA, celestiaChain, chainB
+}
+
+func NewTransferPaths(chain1, chain2, chain3 *ibctesting.TestChain) (*ibctesting.Path, *ibctesting.Path) {
```
Comment (rootulp) [inline test/pfm/pfm_test.go:53]: also seems like it could be private

File: test/pfm/pfm_test.go [hunk 3]
```diff
@@ -0,0 +1,237 @@
...
+	path2.EndpointB.ChannelConfig.PortID = ibctesting.TransferPort
+	path2.EndpointA.ChannelConfig.Version = types.Version
+	path2.EndpointB.ChannelConfig.Version = types.Version
+
+	return path1, path2
+}
+
+// TestPacketForwardMiddlewareTransfer sends a PFM transfer originating from Celestia to ChainA, then back to Celestia and finally to ChainB.
+// It verifies that Celestia forwards the packet successfully, the balance of the sender account on Celestia decreases by the amount sent,
+// and the balance of the receiver account on ChainB increases by the amount sent.
```
Comment (rootulp) [inline test/pfm/pfm_test.go:70]: [out of curiosity] why Celestia -> chain A -> Celestia -> chain B?

Since we're only testing PFM, why not: chain A -> Celestia -> Chain B?

File: test/pfm/pfm_test.go [hunk 4]
```diff
@@ -0,0 +1,237 @@
...
+	celestiaApp := celestia.App.(*app.App)
+	originalCelestiaBalalance := celestiaApp.BankKeeper.GetBalance(celestia.GetContext(), celestia.SenderAccount.GetAddress(), sdk.DefaultBondDenom)
+
+	// Take half of the original balance
+	transferAmount := originalCelestiaBalalance.Amount.QuoRaw(2)
+	timeoutHeight := clienttypes.NewHeight(1, 300)
+	coinToSendToB := sdk.NewCoin(sdk.DefaultBondDenom, transferAmount)
+
+	// Forward the packet to ChainB
+	secondHopMetaData := &PacketMetadata{
```
Comment (rootulp) [inline test/pfm/pfm_test.go:87]: IMO "D" does not need to be capitalized because it is "metadata"

secondHopMetaData => secondHopMetadata

File: test/pfm/pfm_test.go [hunk 5]
```diff
@@ -0,0 +1,237 @@
...
+	// Transfer path: Celestia -> ChainA -> Celestia -> ChainB
+	msg := types.NewMsgTransfer(path1.EndpointB.ChannelConfig.PortID, path1.EndpointB.ChannelID, coinToSendToB, celestia.SenderAccount.GetAddress().String(), chainA.SenderAccount.GetAddress().String(), timeoutHeight, 0, string(memo))
+
+	res, err := celestia.SendMsgs(msg)
+	require.NoError(t, err)
+
+	packet, err := ibctesting.ParsePacketFromEvents(res.GetEvents())
+	require.NoError(t, err)
+
+	err = ForwardPacket([]*ibctesting.Path{path1, path1, path2}, packet)
```
Comment (rootulp) [inline test/pfm/pfm_test.go:119]: [question] why does path1 appear twice in: `]*ibctesting.Path{path1, path1, path2}` ?

File: test/pfm/setup.go [hunk 6]
```diff
@@ -0,0 +1,226 @@
...
+			App: simapp.DefaultAppVersion,
+		},
+		ChainID: chainID,
+		Height:  1,
+		Time:    coord.CurrentTime.UTC(),
+	}
+
+	txConfig := app.GetTxConfig()
+
+	// create an account to send transactions from
```
Comment (rootulp) [inline test/pfm/setup.go:98]: how does this comment apply to the TestChain below? Can the comment be moved immediately above where an account is created? I would guess that should be immediately above:

```go
		// create an account to send transactions from
		senderAcc := ibctesting.SenderAccount{
			SenderAccount: acc,
			SenderPrivKey: senderPrivKey,
		}
```

File: test/pfm/setup.go [hunk 7]
```diff
@@ -0,0 +1,226 @@
+package pfm
```
Comment (rootulp) [inline test/pfm/setup.go:1]: I think most of the setup functions in this file could be made private

File: test/pfm/simapp.go [hunk 8]
```diff
@@ -0,0 +1,856 @@
...
+		AddRoute(paramproposal.RouterKey, params.NewParamChangeProposalHandler(app.ParamsKeeper)).
+		AddRoute(distrtypes.RouterKey, distr.NewCommunityPoolSpendProposalHandler(app.DistrKeeper)).
+		AddRoute(upgradetypes.RouterKey, upgrade.NewSoftwareUpgradeProposalHandler(app.UpgradeKeeper)).
+		AddRoute(ibcclienttypes.RouterKey, ibcclient.NewClientProposalHandler(app.IBCKeeper.ClientKeeper))
+
+	govConfig := govtypes.DefaultConfig()
+	/*
+		Example of setting gov params:
+		govConfig.MaxMetadataLen = 10000
+	*/
```
Comment (rootulp) [inline test/pfm/simapp.go:380]: can prob delete

File: test/pfm/simapp.go [hunk 9]
```diff
@@ -0,0 +1,856 @@
...
+	govKeeper := govkeeper.NewKeeper(
+		appCodec, keys[govtypes.StoreKey], app.GetSubspace(govtypes.ModuleName), app.AccountKeeper, app.BankKeeper,
+		&stakingKeeper, govRouter, app.MsgServiceRouter(), govConfig,
+	)
+
+	app.GovKeeper = *govKeeper.SetHooks(
+		govtypes.NewMultiGovHooks(
+		// register the governance hooks
```
Comment (rootulp) [inline test/pfm/simapp.go:388]: can delete

**Review by rootulp — COMMENTED** [review]
Sorry for delayed review

File: test/pfm/pfm_test.go (hunk 3 above)
Comment (ninabarbakadze) [reply test/pfm/pfm_test.go:70]: because if we were to have this path: chain A -> Celestia -> Chain B tokenfilter would reject the transaction because it would not be tia but rather ibc denom prefixed with channel and port ids. 

In the way i did it first, when we initiate a transfer on Celestia and route that through chain A back to Celestia for forwarding it will unwind and become the native denom again.

File: test/pfm/pfm_test.go (hunk 5 above)
Comment (ninabarbakadze) [reply test/pfm/pfm_test.go:119]: because we have three hops and two of them are between chains Celestia and Chain A. Those chains are path1.

1st hop: Celestia -> Chain A (path1)
2nd hop: Chain A -> Celestia (path1)
3rd hop: Celestia -> Chain B (path2)

File: test/pfm/setup.go (hunk 6 above)
Comment (ninabarbakadze) [reply test/pfm/setup.go:98]: yeah sure i copied this from ibc
