### PR TITLE
fix(multiplexer): shut down on CTRL + C

### LINKED ISSUE #4763: Multiplexer doesn't gracefully shut down on CTRL + C
## Context

On v4.0.0-rc3

## Problem

I hit `CTRL + C` multiple times but I can't exit the multiplexer.

```logs
3:26PM INF finalized block block_app_hash=B6CC5814257136259DE475FF546BB5D161AA94589BE91AE23DDFB2580D44ADB5 height=29 module=state num_txs_res=0 num_val_updates=0
3:26PM INF executed block app_hash=B6CC5814257136259DE475FF546BB5D161AA94589BE91AE23DDFB2580D44ADB5 height=29 module=state
3:26PM INF committed state block_app_hash=A7180E3EC2C034BC98D5877232C40806A17FD19E2A16B485EAB02C507CD99A61 height=29 module=state
^C3:26PM ERR canceled grpc subscription. retrying module=rpc
3:26PM INF service stop impl="P2P Switch" module=p2p msg="Stopping P2P Switch service"
^[[A
3:26PM ERR Failed to subscribe to new blocks. retrying err="service is shutting down" module=rpc retry_number=1
^C^C^C^C^C^C3:26PM ERR Failed to subscribe to new blocks. retrying err="service is shutting down" module=rpc retry_number=2


^C^C3:26PM ERR Failed to subscribe to new blocks. retrying err="service is shutting down" module=rpc retry_number=3
^C^C^C^C^C3:26PM ERR Failed to subscribe to new blocks. retrying err="service is shutting down" module=rpc retry_number=4

^C
^C3:26PM ERR Failed to subscribe to new blocks. retrying err="service is shutting down" module=rpc retry_number=5

^C
^C







^C
^C
```

### PR DESCRIPTION
**Pull request by evan-forbes**
stops the multiplexer from hitting its mutex twice, which will happen if comet calls an abci method _during_ cleanup.

takes a while to hit, but if you decrease the block time it gets hit more. Its still pretty difficult to hit ,which made it kinda hard to debug

a full fix would probably require a larger refactor. closing comet before taking the mutex is maybe another solution, but this is fast and I know it works. if it didn't take so long to hit I might try other approaches

closes #4763

### CODE REVIEW

File: multiplexer/abci/multiplexer.go [hunk 1]
```diff
@@ -52,6 +53,9 @@ const (
 type Multiplexer struct {
 	logger log.Logger
 	mu     sync.Mutex
+	// done is a hack to prevent the multiplexer from catching the above mutex twice and avoiding mu.TryLock
+	// as that could result in an accidental crash.
+	done atomic.Bool
```
Comment (evan-forbes) [inline multiplexer/abci/multiplexer.go:58]: per comments, this is a hack and a longer term solution likely involves a refactor. I could have used TryLock on the mutex, but I was worried that that was not explicit enough and maybe could be hit if we accidentally call the mutex twice

File: multiplexer/abci/multiplexer.go [hunk 2]
```diff
@@ -450,9 +454,12 @@ func openTraceWriter(traceWriterFile string) (w io.WriteCloser, err error) {
 
 // getApp gets the appropriate app based on the latest application version.
 func (m *Multiplexer) getApp() (servertypes.ABCI, error) {
```
Comment (tac0turtle) [inline multiplexer/abci/multiplexer.go:456]: it seems like everywhere getApp is called we have a context. did you try passing the context here for cancellation? it may be hard to verify on all flows as im not sure comet uses contexts correctly for shutdown?

**Review by cmwaters — APPROVED** [review]
Makes sense. There's no case for restarting the multiplexer right? i.e. where you'd need to set the done from true to false again?

**Comment by evan-forbes** [comment]
> There's no case for restarting the multiplexer right?

not after we start the cleanup I don't think no
