### PR TITLE
fix: InitUnlockedBalance unlocked from the vesting balance

### LINKED ISSUE #2295: InitUnlockedBalance will be unlocked from the vesting balance instead of being extra balance
### Summary

Currently, the behavior of the InitUnlockedBalance feature involves adding an extra unlocked balance to the locked accounts. However, there's a need to reconsider this approach and change it based on the [made decision](https://celestia-team.slack.com/archives/C04KS5R9VQU/p1692262592113819?thread_ts=1692205029.302239&cid=C04KS5R9VQU). 

### Problem Definition

To have a vesting account installed in the genesis file, the total allocation of that account is set to `OriginalVestingBalance` and the same amount is also set in the banking module.
I order to have a `total_allocation` locked and e.g. `1TIA` unlocked, the procedure is as follows:
`account.OriginalVestingBalance = total_allocation`
`account.BalanceInBankModule = total_allocation + 1TIA`
which means that account receives `1TIA` more, now the leadership decided instead of donating `1TIA` to each vesting account, we unlock `1TIA` from their locked allocation. Therefore, we need to subtract it from their total allocation. 
So:
`account.OriginalVestingBalance = total_allocation - 1TIA`
`account.BalanceInBankModule = total_allocation`

Same goal achieved without donating extra balance.

### Proposal

It is simple to do that.
Currently the functions that receive vesting account's details and generate a genesis version with its balances, have the following line of code to add extra unlocked amount:

```golang
balance = banktypes.Balance{
		Address: address,
		Coins:   initUnlockedCoins.Add(vestingBalance...),
	}
```

we need to change that code to the following:
```golang
balance = banktypes.Balance{
		Address: address,
		Coins:   vestingBalance,
	}
vestingBalance = vestingBalance.Sub(initUnlockedCoins...)
```

there are 3 functions that need to be modified:

1. NewGenesisDelayedVestingAccount
2. NewGenesisPeriodicVestingAccount
3. NewGenesisContinuousVestingAccount

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by mojtaba-esk**
closes #2295 
more context in the issue.
A short summary: To install a vesting account in the genesis file, allocate the desired amount to `OriginalVestingBalance` and the banking module. For instance, to lock a `total_allocation` and unlock `1TIA`, follow these steps:

    Set `account.OriginalVestingBalance = total_allocation`.
    Set `account.BalanceInBankModule = total_allocation + 1TIA`.

However, to avoid donating extra funds, a new approach is adopted: unlock `1TIA` from the vested amount. This is achieved by subtracting `1TIA` from the `OriginalVestingBalance`:

    Update `account.OriginalVestingBalance = total_allocation - 1TIA`.
    Keep `account.BalanceInBankModule = total_allocation`.

This achieves the same goal without additional donations.

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

File: pkg/genesis/vesting_accounts.go [hunk 1]
```diff
@@ -45,8 +45,9 @@ func NewGenesisDelayedVestingAccount(
 
 	balance = banktypes.Balance{
 		Address: address,
-		Coins:   initUnlockedCoins.Add(vestingBalance...),
+		Coins:   vestingBalance,
 	}
+	vestingBalance = vestingBalance.Sub(initUnlockedCoins...)
```
Comment (staheri14) [inline pkg/genesis/vesting_accounts.go:50]: [Suggestion, optional] `Sub` may cause panic if it results in a negative value; it could be worth mentioning the possibility of panic in the `NewGenesisDelayedVestingAccount` description. Ditto other modified functions in this PR.

File: pkg/genesis/vesting_accounts.go [hunk 2]
```diff
@@ -68,8 +69,9 @@ func NewGenesisPeriodicVestingAccount(
...
```
Comment (staheri14) [inline pkg/genesis/vesting_accounts.go:74]: [Suggestion] Since this change modifies how the function worked before, it's a good idea to note in the function description that the vesting account balance is now calculated by subtracting `initUnlockedCoins` from `vestingBalance`.

**Review by staheri14 — COMMENTED** [review]
Looks good to me! I've included a few suggestions. Defer it to other reviewers for final approval.

**Review by cmwaters — APPROVED** [review]

**Review by evan-forbes — APPROVED** [review]
doesn't have to be done in this PR, but given its importance can we make sure that the total expected balance is tested for @mojtaba-esk? I believe we've discussed this before as invariants or having tx fail/pass depending on time and balance, but also for the perhaps we also need them for vesting module tests. Feel free to grab a slot on my calendar if we need to sync on this :slightly_smiling_face:

**Review by cmwaters — APPROVED** [review]
