### PR TITLE
test: fix mocha nightly test

### LINKED ISSUE #5541: TestStateSyncMocha fails due to `runtime error: index out of range [0] with length 0`
## Context

The nightly tests to state sync Mocha has been failing for the past 3 days

https://github.com/celestiaorg/celestia-app/actions/workflows/test-nightly.yml

## Problem

https://github.com/celestiaorg/celestia-app/actions/runs/16897402900/job/47869693617#step:6:103

```
    logger.go:146: 2025-08-12T02:40:45.887Z	INFO	Exec	{"validator": false, "i": 0, "chain_id": "mocha-4", "test": "TestCelestiaTestSuite/TestStateSyncMocha", "image": "ghcr.io/celestiaorg/celestia-app:7e7bdc82", "test_name": "TestCelestiaTestSuite/TestStateSyncMocha", "command": "celestia-appd init mocha-4-fn-0-TestCelestiaTestSuite_TestStateSyncMocha --chain-id mocha-4 --home /var/cosmos-chain/mocha", "env,": [], "hostname": "TestCelestiaTestSuite_TestStateSyncMocha-zkfydo", "container": "TestCelestiaTestSuite_TestStateSyncMocha-zkfydo"}
    panic.go:115: test panicked: runtime error: index out of range [0] with length 0
        goroutine 36 [running]:
        runtime/debug.Stack()
```

## Proposal

Make the test pass

### PR DESCRIPTION
**Pull request by chatton**
## Overview

Update to v0.2.2 which fixes an index out of bounds error in tastora

triggered nightly run with this change https://github.com/celestiaorg/celestia-app/actions/runs/17039499893

closes #5541

### CODE REVIEW

File: test/docker-e2e/e2e_test.go [hunk 1]
```diff
@@ -356,7 +356,7 @@ func (s *CelestiaTestSuite) validateNodesNotHalted(ctx context.Context, chain ta
 	var haltedNodes []string
 	for i, n := range chain.GetNodes() {
 		// Only check validator nodes for height consistency
-		if n.GetType() != validatorNodeTypeString {
```
Comment (rootulp) [inline test/docker-e2e/e2e_test.go:359]: [no change needed] I wonder if `validatorNodeTypeString` is also removable now

Comment (chatton) [reply test/docker-e2e/e2e_test.go:359]: there were some other fields too that were unused so I just removed them all

**Comment by chatton** [comment]
sorry @rootulp one more fix was made! 🙏
