### PR TITLE
fix: refactor the e2e liveness check

### LINKED ISSUE #5478: `validator liveness check failed`
## Context

https://github.com/celestiaorg/celestia-app/actions/runs/16813243743/job/47623567273?pr=5332

## Problem

```
    e2e_test.go:327: Found 3 unique proposers across 9 blocks
    e2e_test.go:354: Checking 3 total validators for proposer activity from height 3 to 12 (validators at start: 3, validators at end: 3)
    e2e_simple_test.go:62: 
        	Error Trace:	/home/runner/work/celestia-app/celestia-app/test/docker-e2e/e2e_simple_test.go:62
        	Error:      	Received unexpected error:
        	            	1 validator node(s) halted below expected height 12: [node_2 (height_11)]
        	Test:       	TestCelestiaTestSuite/TestE2ESimple
        	Messages:   	validator liveness check failed
```

cc: @mojtaba-esk

### PR DESCRIPTION
**Pull request by evan-forbes**
hack to give the e2e liveness check some breathing room and also just refactor.

the best fix would involve doing a more complex check to see if a node actually halted and if so for what reason. This is not that, therefore doesn't cl0se #5481 imo, however might (at least for now) close #5478

likely reduces flakiness

### CODE REVIEW

File: test/docker-e2e/e2e_test.go [hunk 1]
```diff
@@ -383,11 +361,14 @@ func (s *CelestiaTestSuite) validateNodesNotHalted(ctx context.Context, chain ta
...
 		}
+
 		status, err := nodeClient.Status(ctx)
 		if err != nil {
 			return fmt.Errorf("failed to get status for node %d: %w", i, err)
 		}
-		if status.SyncInfo.LatestBlockHeight < endHeight {
+
+		// the +10 is just to leave room for error
+		if (status.SyncInfo.LatestBlockHeight + 10) < endHeight {
```
Comment (evan-forbes) [inline test/docker-e2e/e2e_test.go:371]: this is the only change to reduce error

it used to be that if a single node was even slightly behind it would fail.

we could reduce this number and potentially catch more bugs, imo that is what #5481 is for where we'd look for more specific failures and stop relying on block height alone to tell us if nodes halted

File: test/docker-e2e/e2e_test.go [hunk 2]
```diff
@@ -329,31 +317,21 @@ func (s *CelestiaTestSuite) fetchProposerAddresses(ctx context.Context, rpcClien
 }
 
 // validateAllValidatorsProposed ensures every validator proposed at least one block
-func (s *CelestiaTestSuite) validateAllValidatorsProposed(startValidators, endValidators *coretypes.ResultValidators, proposerAddresses []string, startHeight, endHeight int64) error {
-	// Convert slice to map for O(1) lookups
+func (s *CelestiaTestSuite) validateAllValidatorsProposed(endValidators *coretypes.ResultValidators, proposerAddresses []string, endHeight int64) error {
```
Comment (evan-forbes) [inline test/docker-e2e/e2e_test.go:320]: this is an optional refactor 

there's no reason to look at both start and end validators when we can just look at end validators.

File: test/docker-e2e/e2e_test.go [hunk 3]
```diff
@@ -257,25 +257,13 @@ func (s *CelestiaTestSuite) ensureMinimumBlocks(ctx context.Context, chain tasto
...
-
-	blocksProduced := endHeight - startHeight
-	s.T().Logf("Checking validator liveness from height %d to %d (%d blocks)", startHeight, endHeight, blocksProduced)
-
-	startValidators, err := rpcClient.Validators(ctx, &startHeight, nil, nil)
-	if err != nil {
-		return nil, nil, fmt.Errorf("validators query at start height %d: %w", startHeight, err)
-	}
-
+func (s *CelestiaTestSuite) fetchValidatorSets(ctx context.Context, rpcClient rpcclient.Client, endHeight int64) (*coretypes.ResultValidators, error) {
```
Comment (evan-forbes) [inline test/docker-e2e/e2e_test.go:260]: this is an optional refactor

we remove the start height as its known, and we only care about the validators at the end of the test

File: test/docker-e2e/e2e_test.go (hunk 1 above)
Comment (evan-forbes) [reply test/docker-e2e/e2e_test.go:371]: could be reduced to 2 and we should get most of the benefit of 10, so will defer to reviewers on this

File: test/docker-e2e/e2e_block_sync_test.go [hunk 4]
```diff
@@ -110,7 +110,7 @@ func (s *CelestiaTestSuite) TestBlockSync() {
 
 	s.T().Logf("Checking validator liveness from height %d", initialHeight)
```
Comment (mojtaba-esk) [inline test/docker-e2e/e2e_block_sync_test.go:111]: `initialHeight` is no longer needed to be here.

File: test/docker-e2e/e2e_full_stack_pfb_test.go [hunk 5]
```diff
@@ -87,7 +87,7 @@ func (s *CelestiaTestSuite) TestE2EFullStackPFB() {
 
 	s.T().Logf("Checking validator liveness from height %d", startHeight)
```
Comment (mojtaba-esk) [inline test/docker-e2e/e2e_full_stack_pfb_test.go:88]: `startHeight` is no longer needed.

File: test/docker-e2e/e2e_simple_test.go [hunk 6]
```diff
@@ -60,7 +60,7 @@ func (s *CelestiaTestSuite) TestE2ESimple() {
 
 	s.T().Logf("Checking validator liveness from height %d", startHeight)
```
Comment (mojtaba-esk) [inline test/docker-e2e/e2e_simple_test.go:61]: `startHeight` is no longer needed.

File: test/docker-e2e/e2e_state_sync_test.go [hunk 7]
```diff
@@ -128,7 +128,7 @@ func (s *CelestiaTestSuite) TestStateSync() {
 
 	s.T().Logf("Checking validator liveness from height %d", initialHeight)
```
Comment (mojtaba-esk) [inline test/docker-e2e/e2e_state_sync_test.go:129]: `initialHeight` is no longer needed.

File: test/docker-e2e/e2e_test.go (hunk 3 above)
Comment (mojtaba-esk) [reply test/docker-e2e/e2e_test.go:260]: This simplifies the code considerably.

**Review by mojtaba-esk — APPROVED** [review]
Thanks for the fix
